runtime: nodejs12

handlers:
  - url: /static
    static_dir: build/static

  - url: /(.*\.(json|ico|js|svg))$
    static_files: build/\1
    upload: build/.*\.(json|ico|js|svg)$

  - url: .*
    static_files: build/index.html
    upload: build/index.html
    secure: always

env_variables:
  NODE_ENV: 'production'